FORMAT: 1A
HOST: http://vmpro.eh.mi24.tv

# vmpro
VMPRO API is a *short texts saving* service similar to its physical paper presence on your table.


# Group SERVICEOBJECT
Beschreibung für das SERVICEOBJECT

## Create and List of SERVICEOBJECT [/base-url]

### List of existing SERVICEOBJECTs [GET]
Use this to retrieve a list of all existing SERVICEOBJECTS
+ Response 200 (application/json)

        [{"id": 1, "property": "value" }, {"id": 2, "property": "value" }]

### Create new SERVICEOBJECT [POST]
This create an new SERVICEOBJECT
+ Request (application/json)

        {"property": "value" }

+ Response 201

## Manipulate SERVICEOBJECT [/base-url/{theId}]
+ Parameters
    + theId (required, number, `2`) ... Numeric `id` of the VideoManager to perform action with. Has example value.

### Get SERVICEOBJECT [GET]
+ Response 200 (application/json)

        {"id": 1, "property": "value" }

### Update complete SERVICEOBJECT [PUT]
+ Request (application/json)

        {"id": 1, "property": "newvalue" }

+ Response 204

### Update parts of SERVICEOBJECT [PATCH]
+ Request (application/json)

        {"id": 1, "property": "newvalue" }

+ Response 204

### Delete SERVICEOBJECT [DELETE]
+ Response 204






# Group Trash Items
Deleted video blah

## Trash Item Collection [/vam/rest/vms/{videoManagerId}/trash]
A list of all video objects in trashcan as an array of objects

+ Parameters
    + videoManagerId (required, number, `2`) ... Numeric `id` of the VideoManager to perform action with. Has example value.

### List all Trash Items [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "properties and values of video object needed"
        }, {
          "id": 2, "title": "properties and values of video object needed"
        }]



# Group Embed Types
Embed Types related resources of the **VMPRO API**

## Embed Types Collection [/vam/rest/vms/{videoManagerId}/embedtype]
A list of all Embed Types as an array of objects

+ Parameters
    + videoManagerId (required, number, `2`) ... Numeric `id` of the VideoManager to perform action with. Has example value.

### List all Embed Types [GET]
+ Response 200 (application/json)

        [{
          "id": "HTML_CODE"
        }, {
          "id": "LINK_URL"
        }]


# Group Player
Player related resources of the **VMPRO API**

## Player Collection [/vam/rest/vms/{videoManagerId}/player]
A list of all Players as an array of objects

+ Parameters
    + videoManagerId (required, number, `2`) ... Numeric `id` of the VideoManager to perform action with. Has example value.

### List all Players [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Player default (APIARY)"
        }, {
          "id": 2, "title": "Player green (APIARY)"
        }]



# Group Embed Codes
Embed Codes related resources of the **VMPRO API**


## Embed Code [/vam/rest/vms/{videoManagerId}/video/{videoId}/player/{playerId}/embedcode/{embedTypeId}]
A single Embed Code object with all its details

+ Parameters
    + videoManagerId (required, number, `2`) ... Numeric `id` of the VideoManager to perform action with. Has example value.
    + videoId (required, string, `74WGsUCJ3QJMjN8-LeYFpm`) ... string `id` of the selected video to perform action with. Has example value.
    + playerId (required, number, `2`) ... Numeric `id` of the Player to perform action with. Has example value.
    + embedTypeId (required, string, `HTML_CODE`) ... string `id` of the Player to perform action with. Has example value.

### Retrieve an Embed Code [GET]
+ Response 200 (application/json)

        {
          "id": "HTML_CODE",
          "code": "<mi24-video video-id="74WGsUCJ3QJMjN8-LeYFpm" player-id="2" config-type="vmpro" url="//d.video-cdn.net"></mi24-video><script src="//e.video-cdn.net/elfriede.js"></script>"
        }






# Group Statistics
Hier können die verschienden Reports bezogen werden.


## Coverage [/vam/rest/vms/{videoManagerId}/statistics/report/coverage{?video-id,start-date,end-date}]
+ Parameters
    + videoManagerId (required, number, `2`) ... Numeric `id` of the VideoManager to perform action with. Has example value.
    + video-id (required, string, `74WGsUCJ3QJMjN8-LeYFpm`) ... String `id` of the selected video to perform action with
    + start-date (required, number, `1388530800000`) ... Numeric `value` of start date
    + end-date (required, number, `1388530800000`) ... Numeric `value` of end date

### Get statistics report for coverage [GET]
+ Response 200 (application/json)

        {
            "totalLength": 12000,
            "data": [
                {
                    "timeStamp": 5000,
                    "value": 5
                },
                {
                    "timeStamp": 5000,
                    "value": 3
                }
            ]
        }


## Views [/vam/rest/vms/{videoManagerId}/statistics/report/views{?video-id,start-date,end-date}]
+ Parameters
    + videoManagerId (required, number, `2`) ... Numeric `id` of the VideoManager to perform action with. Has example value.
    + video-id (required, string, `74WGsUCJ3QJMjN8-LeYFpm`) ... String `id` of the selected video to perform action with
    + start-date (required, number, `1388530800000`) ... Numeric `value` of start date
    + end-date (required, number, `1388530800000`) ... Numeric `value` of end date
    
### Get statistics report for views [GET]
+ Response 200 (application/json)

        [
            {
                "timeStamp": 1388530800000,
                "value": 5
            },
            {
                "timeStamp": 1388617200000,
                "value": 10
            }
        ]


## Plays [/vam/rest/vms/{videoManagerId}/statistics/report/plays{?video-id,start-date,end-date}]
+ Parameters
    + videoManagerId (required, number, `2`) ... Numeric `id` of the VideoManager to perform action with. Has example value.
    + video-id (required, string, `74WGsUCJ3QJMjN8-LeYFpm`) ... String `id` of the selected video to perform action with
    + start-date (required, number, `1388530800000`) ... Numeric `value` of start date
    + end-date (required, number, `1388530800000`) ... Numeric `value` of end date
    
### Get statistics report for plays [GET]
+ Response 200 (application/json)

        [
            {
                "timeStamp": 1388530800000,
                "value": 3
            },
            {
                "timeStamp": 1388617200000,
                "value": 8
            }
        ]


# Group Video Manager
Get, create or update Video-Managers

## Video-Managers [/vam/rest/vms]

### List of existing Video-Manages [GET]
+ Response 200 (application/json)
        
        [{"id": 1, "name": "Video Manager 1" }, {"id": 2, "name": "Video Manager 2" }]

### Create new Video-Manager [POST]
This creates a new Video-Manager

+ Request (application/json)

    + Body

            {
                "name": "Video Manager 3",
                "owner": "admin@mi24.tv",
                "company": "Customer company name",
                "department": "Customer department name",
                "plans": {
                    "trafficQuota": 100,
                    "userQuota": 25,
                    "storageQuota": 200
                },
                "transcodingProfiles": [
                    {
                        "key": "abc700",
                        "quality": "480p",
                        "videoExtension": "mp4",
                        "stillExtension": "jpeg",
                        "createStill": true,
                        "container": {
                            "name": "isom",
                            "properties": {}
                        },
                        "video": {
                            "codec": {
                                "name": "h264",
                                "properties": {}
                            },
                            "resolution": {
                                "width": 640,
                                "height": 480
                            },
                            "keyFrame": 50,
                            "frameRate": 25,
                            "bitRate": 1250,
                            "aspectRatio": {
                                "width": 4,
                                "height": 3
                            }
                        },
                        "audio": {
                            "codec": {
                                "name": "aac",
                                "properties": {}
                            },
                            "channels": 2,
                            "bitRate": 128,
                            "sampleRate": 44100
                        }
                    }
                ],
                "playerSkins": [
                    {
                        "name": "hrt",
                        "skinDownloadUrl": "http://ccc.mi24.dev/skins/skin_png.1",
                         "playButton": {
                            "dimension": {
                                "width": 100,
                                "height": 100
                            },
                            "position": {
                                "x": 280,
                                "y": 0
                            }
                        },
                        "stopButton": {
                            "dimension": {
                                "width": 100,
                                "height": 100
                            },
                            "position": {
                                "x": 280,
                                "y": 0
                            }
                        },
                        "slider": {
                          "dimension": {
                              "width": 100,
                              "height": 100
                          },
                          "position": {
                              "x": 280,
                              "y": 0
                          }
                        },
                        "mute": {
                          "dimension": {
                              "width": 100,
                              "height": 100
                          },
                          "position": {
                              "x": 280,
                              "y": 0
                          }
                        },
                        "volume": {
                          "dimension": {
                              "width": 100,
                              "height": 100
                          },
                          "position": {
                              "x": 280,
                              "y": 0
                          }
                        },
                        "fullscreen": {
                          "dimension": {
                              "width": 100,
                              "height": 100
                          },
                          "position": {
                              "x": 280,
                              "y": 0
                          }
                        },
                        "colors": {
                          "slider": {
                              "text": "fff000",
                              "progress": "fff000",
                              "background": "fff000"
                          },
                          "button": {
                              "active": "fff000",
                              "default": "fff000",
                              "hover": "fff000"
                          },
                          "background": {
                              "default": "fff000"
                          }
                      }
                    }
                ]
            }
        
    + Schema
    
            {
                "type": "object",
                "$schema": "http://json-schema.org/draft-03/schema",
                "id": "http://jsonschema.net",
                "required": true,
                "properties": {
                    "company": {
                        "type": "string",
                        "id": "http://jsonschema.net/company",
                        "required": true
                    },
                    "department": {
                        "type": "string",
                        "id": "http://jsonschema.net/department",
                        "required": true
                    },
                    "name": {
                        "type": "string",
                        "id": "http://jsonschema.net/name",
                        "required": true
                    },
                    "owner": {
                        "type": "string",
                        "id": "http://jsonschema.net/owner",
                        "required": true
                    },
                    "plans": {
                        "type": "object",
                        "id": "http://jsonschema.net/plans",
                        "required": true,
                        "properties": {
                            "storageQuota": {
                                "type": "number",
                                "id": "http://jsonschema.net/plans/storageQuota",
                                "required": true
                            },
                            "trafficQuota": {
                                "type": "number",
                                "id": "http://jsonschema.net/plans/trafficQuota",
                                "required": true
                            },
                            "userQuota": {
                                "type": "number",
                                "id": "http://jsonschema.net/plans/userQuota",
                                "required": true
                            }
                        }
                    },
                    "transcodingProfiles": {
                        "type": "array",
                        "id": "http://jsonschema.net/transcodingProfiles",
                        "required": true,
                        "items": {
                            "type": "object",
                            "id": "http://jsonschema.net/transcodingProfiles/0",
                            "required": true,
                            "properties": {
                                "audio": {
                                    "type": "object",
                                    "id": "http://jsonschema.net/transcodingProfiles/0/audio",
                                    "required": true,
                                    "properties": {
                                        "bitRate": {
                                            "type": "number",
                                            "id": "http://jsonschema.net/transcodingProfiles/0/audio/bitRate",
                                            "required": true
                                        },
                                        "channels": {
                                            "type": "number",
                                            "id": "http://jsonschema.net/transcodingProfiles/0/audio/channels",
                                            "required": true
                                        },
                                        "codec": {
                                            "type": "object",
                                            "id": "http://jsonschema.net/transcodingProfiles/0/audio/codec",
                                            "required": true,
                                            "properties": {
                                                "name": {
                                                    "type": "string",
                                                    "id": "http://jsonschema.net/transcodingProfiles/0/audio/codec/name",
                                                    "required": true
                                                },
                                                "properties": {
                                                    "type": "object",
                                                    "id": "http://jsonschema.net/transcodingProfiles/0/audio/codec/properties",
                                                    "required": true
                                                }
                                            }
                                        },
                                        "sampleRate": {
                                            "type": "number",
                                            "id": "http://jsonschema.net/transcodingProfiles/0/audio/sampleRate",
                                            "required": true
                                        }
                                    }
                                },
                                "container": {
                                    "type": "object",
                                    "id": "http://jsonschema.net/transcodingProfiles/0/container",
                                    "required": true,
                                    "properties": {
                                        "name": {
                                            "type": "string",
                                            "id": "http://jsonschema.net/transcodingProfiles/0/container/name",
                                            "required": true
                                        },
                                        "properties": {
                                            "type": "object",
                                            "id": "http://jsonschema.net/transcodingProfiles/0/container/properties",
                                            "required": true
                                        }
                                    }
                                },
                                "createStill": {
                                    "type": "boolean",
                                    "id": "http://jsonschema.net/transcodingProfiles/0/createStill",
                                    "required": true
                                },
                                "key": {
                                    "type": "string",
                                    "id": "http://jsonschema.net/transcodingProfiles/0/key",
                                    "required": true
                                },
                                "quality": {
                                    "type": "string",
                                    "id": "http://jsonschema.net/quality",
                                    "required": true
                                },
                                "stillExtension": {
                                    "type": "string",
                                    "id": "http://jsonschema.net/transcodingProfiles/0/stillExtension",
                                    "required": true
                                },
                                "videoExtension": {
                                    "type": "string",
                                    "id": "http://jsonschema.net/transcodingProfiles/0/videoExtension",
                                    "required": true
                                },
                                "video": {
                                    "type": "object",
                                    "id": "http://jsonschema.net/transcodingProfiles/0/video",
                                    "required": true,
                                    "properties": {
                                        "aspectRatio": {
                                            "type": "object",
                                            "id": "http://jsonschema.net/transcodingProfiles/0/video/aspectRatio",
                                            "required": true,
                                            "properties": {
                                                "height": {
                                                    "type": "number",
                                                    "id": "http://jsonschema.net/transcodingProfiles/0/video/aspectRatio/height",
                                                    "required": true
                                                },
                                                "width": {
                                                    "type": "number",
                                                    "id": "http://jsonschema.net/transcodingProfiles/0/video/aspectRatio/width",
                                                    "required": true
                                                }
                                            }
                                        },
                                        "bitRate": {
                                            "type": "number",
                                            "id": "http://jsonschema.net/transcodingProfiles/0/video/bitRate",
                                            "required": true
                                        },
                                        "codec": {
                                            "type": "object",
                                            "id": "http://jsonschema.net/transcodingProfiles/0/video/codec",
                                            "required": true,
                                            "properties": {
                                                "name": {
                                                    "type": "string",
                                                    "id": "http://jsonschema.net/transcodingProfiles/0/video/codec/name",
                                                    "required": true
                                                },
                                                "properties": {
                                                    "type": "object",
                                                    "id": "http://jsonschema.net/transcodingProfiles/0/video/codec/properties",
                                                    "required": true
                                                }
                                            }
                                        },
                                        "frameRate": {
                                            "type": "number",
                                            "id": "http://jsonschema.net/transcodingProfiles/0/video/frameRate",
                                            "required": true
                                        },
                                        "keyFrame": {
                                            "type": "number",
                                            "id": "http://jsonschema.net/transcodingProfiles/0/video/keyFrame",
                                            "required": true
                                        },
                                        "resolution": {
                                            "type": "object",
                                            "id": "http://jsonschema.net/transcodingProfiles/0/video/resolution",
                                            "required": true,
                                            "properties": {
                                                "height": {
                                                    "type": "number",
                                                    "id": "http://jsonschema.net/transcodingProfiles/0/video/resolution/height",
                                                    "required": true
                                                },
                                                "width": {
                                                    "type": "number",
                                                    "id": "http://jsonschema.net/transcodingProfiles/0/video/resolution/width",
                                                    "required": true
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }


+ Response 201

    + Header
        
            Location: http://localhost:3000/vam/rest/vms/3
                  
## Specific Video-Manager [/vam/rest/vms/{videoManagerId}]
+ Parameters
    + videoManagerId (required, number, `3`) ... Numeric `id` of the VideoManager to perform action with.

### Get Video-Manager [GET] 
+ Response 200 (application/json)
    
        {
            "id": 3,
            "name": "Video Manager 3"
        }

# Group Transcoding Profiles
Update or add Transcoding Profiles
 
## Transcoding Profiles [/vam/rest/vms/{videoManagerId}/transcoding-profiles/{transcodingProfileKey}]
+ Parameters
    + videoManagerId (required, number, `3`) ... Numeric `id` of the VideoManager to perform action with.
    + transcodingProfileKey (required, string, `480p`) ... string `key` (`id`) of the Transcoding Profile to add or update.

### Add new or update existing Transcoding Profile [PUT]
 
+ Request (application/json)
    
    + Body
     
            {
                "key": "abc700",
                "quality": "480p",
                "videoExtension": "mp4",
                "stillExtension": "jpeg",
                "createStill": true,
                "container": {
                    "name": "isom",
                    "properties": {}
                },
                "video": {
                    "codec": {
                        "name": "h264",
                        "properties": {
                            "profile": "main",
                            "preset": "fast"
                        }
                    },
                    "resolution": {
                        "width": 640,
                        "height": 480
                    },
                    "keyFrame": 50,
                    "frameRate": 25,
                    "bitRate": 1250,
                    "aspectRatio": {
                        "width": 4,
                        "height": 3
                    }
                },
                "audio": {
                    "codec": {
                        "name": "aac",
                        "properties": null
                    },
                    "channels": 2,
                    "bitRate": 128,
                    "sampleRate": 44100
                }
            }

    + Schema 
        
            {
                "type": "object",
                "$schema": "http://json-schema.org/draft-03/schema",
                "id": "http://jsonschema.net",
                "required": true,
                "properties": {
                    "audio": {
                        "type": "object",
                        "id": "http://jsonschema.net/audio",
                        "required": true,
                        "properties": {
                            "bitRate": {
                                "type": "number",
                                "id": "http://jsonschema.net/audio/bitRate",
                                "required": true
                            },
                            "channels": {
                                "type": "number",
                                "id": "http://jsonschema.net/audio/channels",
                                "required": true
                            },
                            "codec": {
                                "type": "object",
                                "id": "http://jsonschema.net/audio/codec",
                                "required": true,
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/audio/codec/name",
                                        "required": true
                                    },
                                    "properties": {
                                        "type": "object",
                                        "id": "http://jsonschema.net/audio/codec/properties",
                                        "required": true
                                    }
                                }
                            },
                            "sampleRate": {
                                "type": "number",
                                "id": "http://jsonschema.net/audio/sampleRate",
                                "required": true
                            }
                        }
                    },
                    "container": {
                        "type": "object",
                        "id": "http://jsonschema.net/container",
                        "required": true,
                        "properties": {
                            "name": {
                                "type": "string",
                                "id": "http://jsonschema.net/container/name",
                                "required": true
                            },
                            "properties": {
                                "type": "object",
                                "id": "http://jsonschema.net/container/properties",
                                "required": true
                            }
                        }
                    },
                    "createStill": {
                        "type": "boolean",
                        "id": "http://jsonschema.net/createStill",
                        "required": true
                    },
                    "key": {
                        "type": "string",
                        "id": "http://jsonschema.net/key",
                        "required": true
                    },
                    "quality": {
                        "type": "string",
                        "id": "http://jsonschema.net/quality",
                        "required": true
                    },
                    "stillExtension": {
                        "type": "string",
                        "id": "http://jsonschema.net/stillExtension",
                        "required": true
                    },
                    "videoExtension": {
                        "type": "string",
                        "id": "http://jsonschema.net/videoExtension",
                        "required": true
                    },
                    "video": {
                        "type": "object",
                        "id": "http://jsonschema.net/video",
                        "required": true,
                        "properties": {
                            "aspectRatio": {
                                "type": "object",
                                "id": "http://jsonschema.net/video/aspectRatio",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/video/aspectRatio/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/video/aspectRatio/width",
                                        "required": true
                                    }
                                }
                            },
                            "bitRate": {
                                "type": "number",
                                "id": "http://jsonschema.net/video/bitRate",
                                "required": true
                            },
                            "codec": {
                                "type": "object",
                                "id": "http://jsonschema.net/video/codec",
                                "required": true,
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/video/codec/name",
                                        "required": true
                                    },
                                    "properties": {
                                        "type": "object",
                                        "id": "http://jsonschema.net/video/codec/properties",
                                        "required": true,
                                        "properties": {
                                            "preset": {
                                                "type": "string",
                                                "id": "http://jsonschema.net/video/codec/properties/preset",
                                                "required": true
                                            },
                                            "profile": {
                                                "type": "string",
                                                "id": "http://jsonschema.net/video/codec/properties/profile",
                                                "required": true
                                            }
                                        }
                                    }
                                }
                            },
                            "frameRate": {
                                "type": "number",
                                "id": "http://jsonschema.net/video/frameRate",
                                "required": true
                            },
                            "keyFrame": {
                                "type": "number",
                                "id": "http://jsonschema.net/video/keyFrame",
                                "required": true
                            },
                            "resolution": {
                                "type": "object",
                                "id": "http://jsonschema.net/video/resolution",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/video/resolution/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/video/resolution/width",
                                        "required": true
                                    }
                                }
                            }
                        }
                    }
                }
            }

+ Response 200

# Group Plans
Update plans (user, traffic and storage quota).

## Plans [/vam/rest/vms/{videoManagerId}/plans]
+ Parameters
    + videoManagerId (required, number, `3`) ... Numeric `id` of the VideoManager to perform action with.

### Update plans [PUT]
+ Request (application/json)
    
    + Body        
    
            {
                "trafficQuota": 200,
                "userQuota": 50,
                "storageQuota": 500
            }
        
    + Schema 
        
            {
                "type": "object",
                "$schema": "http://json-schema.org/draft-03/schema",
                "id": "http://jsonschema.net",
                "required": true,
                "properties": {
                    "storageQuota": {
                        "type": "number",
                        "id": "http://jsonschema.net/storageQuota",
                        "required": true
                    },
                    "trafficQuota": {
                        "type": "number",
                        "id": "http://jsonschema.net/trafficQuota",
                        "required": true
                    },
                    "userQuota": {
                        "type": "number",
                        "id": "http://jsonschema.net/userQuota",
                        "required": true
                    }
                }
            }
        
+ Response 200

# Group Player Skin

## Player Skin [/vam/rest/vms/{videoManagerId}/player-skins]

+ Parameters
    + videoManagerId (required, number, `3`) ... Numeric `id` of the Note to perform action with. Has example value.

### Create Player Skin [POST]
    
+ Request (application/json)
  
    + Body
    
            {
                "name": "hrt",
                "skinDownloadUrl": "http://ccc.mi24.dev/skins/skin_png.1",
                "playButton": {
                    "dimension": {
                        "width": 100,
                        "height": 100
                    },
                    "position": {
                        "x": 280,
                        "y": 0
                    }
                },
                "stopButton": {
                    "dimension": {
                        "width": 100,
                        "height": 100
                    },
                    "position": {
                        "x": 280,
                        "y": 0
                    }
                },
                "slider": {
                    "dimension": {
                        "width": 100,
                        "height": 100
                    },
                    "position": {
                        "x": 280,
                        "y": 0
                    }
                },
                "mute": {
                    "dimension": {
                        "width": 100,
                        "height": 100
                    },
                    "position": {
                        "x": 280,
                        "y": 0
                    }
                },
                "volume": {
                    "dimension": {
                        "width": 100,
                        "height": 100
                    },
                    "position": {
                        "x": 280,
                        "y": 0
                    }
                },
                "volumeBackground": {
                    "dimension": {
                        "width": 100,
                        "height": 100
                    },
                    "position": {
                        "x": 280,
                        "y": 0
                    }
                },
                "buttonSeperator": {
                    "dimension": {
                        "width": 100,
                        "height": 100
                    },
                    "position": {
                        "x": 280,
                        "y": 0
                    }
                },
                "sliderBackground": {
                    "dimension": {
                        "width": 100,
                        "height": 100
                    },
                    "position": {
                        "x": 280,
                        "y": 0
                    }
                }, 
                "sliderBuffer": {
                    "dimension": {
                        "width": 100,
                        "height": 100
                    },
                    "position": {
                        "x": 280,
                        "y": 0
                    }
                },
                "sliderProgress": {
                    "dimension": {
                        "width": 100,
                        "height": 100
                    },
                    "position": {
                        "x": 280,
                        "y": 0
                    }
                },                                       
                "fullscreen": {
                    "dimension": {
                        "width": 100,
                        "height": 100
                    },
                    "position": {
                        "x": 280,
                        "y": 0
                    }
                },
                "bigPlayButton": {
                    "customButton": false,
                    "dimension": {
                        "width": 100,
                        "height": 100
                    },
                    "position": {
                        "x": 280,
                        "y": 0
                    }
                },
                "colors": {
                    "slider": {
                        "text": "fff000",
                        "progress": "fff000",
                        "background": "fff000"
                    },
                    "button": {
                        "active": "fff000",
                        "default": "fff000",
                        "hover": "fff000"
                    },
                    "background": {
                        "default": "fff000"
                    }
                }
            }
    
    + Schema
    
            {
                "type": "object",
                "$schema": "http://json-schema.org/draft-03/schema",
                "id": "http://jsonschema.net",
                "required": true,
                "properties": {
                    "bigPlayButton": {
                        "type": "object",
                        "id": "http://jsonschema.net/bigPlayButton",
                        "required": true,
                        "properties": {
                            "customButton": {
                                "type": "boolean",
                                "id": "http://jsonschema.net/bigPlayButton/customButton",
                                "required": true
                            },
                            "dimension": {
                                "type": "object",
                                "id": "http://jsonschema.net/bigPlayButton/dimension",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/bigPlayButton/dimension/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/bigPlayButton/dimension/width",
                                        "required": true
                                    }
                                }
                            },
                            "position": {
                                "type": "object",
                                "id": "http://jsonschema.net/bigPlayButton/position",
                                "required": true,
                                "properties": {
                                    "x": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/bigPlayButton/position/x",
                                        "required": true
                                    },
                                    "y": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/bigPlayButton/position/y",
                                        "required": true
                                    }
                                }
                            }
                        }
                    },
                    "buttonSeperator": {
                        "type": "object",
                        "id": "http://jsonschema.net/buttonSeperator",
                        "required": true,
                        "properties": {
                            "dimension": {
                                "type": "object",
                                "id": "http://jsonschema.net/buttonSeperator/dimension",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/buttonSeperator/dimension/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/buttonSeperator/dimension/width",
                                        "required": true
                                    }
                                }
                            },
                            "position": {
                                "type": "object",
                                "id": "http://jsonschema.net/buttonSeperator/position",
                                "required": true,
                                "properties": {
                                    "x": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/buttonSeperator/position/x",
                                        "required": true
                                    },
                                    "y": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/buttonSeperator/position/y",
                                        "required": true
                                    }
                                }
                            }
                        }
                    },
                    "colors": {
                        "type": "object",
                        "id": "http://jsonschema.net/colors",
                        "required": true,
                        "properties": {
                            "background": {
                                "type": "object",
                                "id": "http://jsonschema.net/colors/background",
                                "required": true,
                                "properties": {
                                    "default": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/colors/background/default",
                                        "required": true
                                    }
                                }
                            },
                            "button": {
                                "type": "object",
                                "id": "http://jsonschema.net/colors/button",
                                "required": true,
                                "properties": {
                                    "active": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/colors/button/active",
                                        "required": true
                                    },
                                    "default": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/colors/button/default",
                                        "required": true
                                    },
                                    "hover": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/colors/button/hover",
                                        "required": true
                                    }
                                }
                            },
                            "slider": {
                                "type": "object",
                                "id": "http://jsonschema.net/colors/slider",
                                "required": true,
                                "properties": {
                                    "background": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/colors/slider/background",
                                        "required": true
                                    },
                                    "progress": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/colors/slider/progress",
                                        "required": true
                                    },
                                    "text": {
                                        "type": "string",
                                        "id": "http://jsonschema.net/colors/slider/text",
                                        "required": true
                                    }
                                }
                            }
                        }
                    },
                    "fullscreen": {
                        "type": "object",
                        "id": "http://jsonschema.net/fullscreen",
                        "required": true,
                        "properties": {
                            "dimension": {
                                "type": "object",
                                "id": "http://jsonschema.net/fullscreen/dimension",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/fullscreen/dimension/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/fullscreen/dimension/width",
                                        "required": true
                                    }
                                }
                            },
                            "position": {
                                "type": "object",
                                "id": "http://jsonschema.net/fullscreen/position",
                                "required": true,
                                "properties": {
                                    "x": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/fullscreen/position/x",
                                        "required": true
                                    },
                                    "y": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/fullscreen/position/y",
                                        "required": true
                                    }
                                }
                            }
                        }
                    },
                    "mute": {
                        "type": "object",
                        "id": "http://jsonschema.net/mute",
                        "required": true,
                        "properties": {
                            "dimension": {
                                "type": "object",
                                "id": "http://jsonschema.net/mute/dimension",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/mute/dimension/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/mute/dimension/width",
                                        "required": true
                                    }
                                }
                            },
                            "position": {
                                "type": "object",
                                "id": "http://jsonschema.net/mute/position",
                                "required": true,
                                "properties": {
                                    "x": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/mute/position/x",
                                        "required": true
                                    },
                                    "y": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/mute/position/y",
                                        "required": true
                                    }
                                }
                            }
                        }
                    },
                    "name": {
                        "type": "string",
                        "id": "http://jsonschema.net/name",
                        "required": true
                    },
                    "playButton": {
                        "type": "object",
                        "id": "http://jsonschema.net/playButton",
                        "required": true,
                        "properties": {
                            "dimension": {
                                "type": "object",
                                "id": "http://jsonschema.net/playButton/dimension",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/playButton/dimension/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/playButton/dimension/width",
                                        "required": true
                                    }
                                }
                            },
                            "position": {
                                "type": "object",
                                "id": "http://jsonschema.net/playButton/position",
                                "required": true,
                                "properties": {
                                    "x": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/playButton/position/x",
                                        "required": true
                                    },
                                    "y": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/playButton/position/y",
                                        "required": true
                                    }
                                }
                            }
                        }
                    },
                    "skinDownloadUrl": {
                        "type": "string",
                        "id": "http://jsonschema.net/skinDownloadUrl",
                        "required": true
                    },
                    "sliderBackground": {
                        "type": "object",
                        "id": "http://jsonschema.net/sliderBackground",
                        "required": true,
                        "properties": {
                            "dimension": {
                                "type": "object",
                                "id": "http://jsonschema.net/sliderBackground/dimension",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/sliderBackground/dimension/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/sliderBackground/dimension/width",
                                        "required": true
                                    }
                                }
                            },
                            "position": {
                                "type": "object",
                                "id": "http://jsonschema.net/sliderBackground/position",
                                "required": true,
                                "properties": {
                                    "x": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/sliderBackground/position/x",
                                        "required": true
                                    },
                                    "y": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/sliderBackground/position/y",
                                        "required": true
                                    }
                                }
                            }
                        }
                    },
                    "sliderBuffer": {
                        "type": "object",
                        "id": "http://jsonschema.net/sliderBuffer",
                        "required": true,
                        "properties": {
                            "dimension": {
                                "type": "object",
                                "id": "http://jsonschema.net/sliderBuffer/dimension",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/sliderBuffer/dimension/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/sliderBuffer/dimension/width",
                                        "required": true
                                    }
                                }
                            },
                            "position": {
                                "type": "object",
                                "id": "http://jsonschema.net/sliderBuffer/position",
                                "required": true,
                                "properties": {
                                    "x": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/sliderBuffer/position/x",
                                        "required": true
                                    },
                                    "y": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/sliderBuffer/position/y",
                                        "required": true
                                    }
                                }
                            }
                        }
                    },
                    "sliderProgress": {
                        "type": "object",
                        "id": "http://jsonschema.net/sliderProgress",
                        "required": true,
                        "properties": {
                            "dimension": {
                                "type": "object",
                                "id": "http://jsonschema.net/sliderProgress/dimension",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/sliderProgress/dimension/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/sliderProgress/dimension/width",
                                        "required": true
                                    }
                                }
                            },
                            "position": {
                                "type": "object",
                                "id": "http://jsonschema.net/sliderProgress/position",
                                "required": true,
                                "properties": {
                                    "x": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/sliderProgress/position/x",
                                        "required": true
                                    },
                                    "y": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/sliderProgress/position/y",
                                        "required": true
                                    }
                                }
                            }
                        }
                    },
                    "slider": {
                        "type": "object",
                        "id": "http://jsonschema.net/slider",
                        "required": true,
                        "properties": {
                            "dimension": {
                                "type": "object",
                                "id": "http://jsonschema.net/slider/dimension",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/slider/dimension/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/slider/dimension/width",
                                        "required": true
                                    }
                                }
                            },
                            "position": {
                                "type": "object",
                                "id": "http://jsonschema.net/slider/position",
                                "required": true,
                                "properties": {
                                    "x": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/slider/position/x",
                                        "required": true
                                    },
                                    "y": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/slider/position/y",
                                        "required": true
                                    }
                                }
                            }
                        }
                    },
                    "stopButton": {
                        "type": "object",
                        "id": "http://jsonschema.net/stopButton",
                        "required": true,
                        "properties": {
                            "dimension": {
                                "type": "object",
                                "id": "http://jsonschema.net/stopButton/dimension",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/stopButton/dimension/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/stopButton/dimension/width",
                                        "required": true
                                    }
                                }
                            },
                            "position": {
                                "type": "object",
                                "id": "http://jsonschema.net/stopButton/position",
                                "required": true,
                                "properties": {
                                    "x": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/stopButton/position/x",
                                        "required": true
                                    },
                                    "y": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/stopButton/position/y",
                                        "required": true
                                    }
                                }
                            }
                        }
                    },
                    "volumeBackground": {
                        "type": "object",
                        "id": "http://jsonschema.net/volumeBackground",
                        "required": true,
                        "properties": {
                            "dimension": {
                                "type": "object",
                                "id": "http://jsonschema.net/volumeBackground/dimension",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/volumeBackground/dimension/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/volumeBackground/dimension/width",
                                        "required": true
                                    }
                                }
                            },
                            "position": {
                                "type": "object",
                                "id": "http://jsonschema.net/volumeBackground/position",
                                "required": true,
                                "properties": {
                                    "x": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/volumeBackground/position/x",
                                        "required": true
                                    },
                                    "y": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/volumeBackground/position/y",
                                        "required": true
                                    }
                                }
                            }
                        }
                    },
                    "volume": {
                        "type": "object",
                        "id": "http://jsonschema.net/volume",
                        "required": true,
                        "properties": {
                            "dimension": {
                                "type": "object",
                                "id": "http://jsonschema.net/volume/dimension",
                                "required": true,
                                "properties": {
                                    "height": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/volume/dimension/height",
                                        "required": true
                                    },
                                    "width": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/volume/dimension/width",
                                        "required": true
                                    }
                                }
                            },
                            "position": {
                                "type": "object",
                                "id": "http://jsonschema.net/volume/position",
                                "required": true,
                                "properties": {
                                    "x": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/volume/position/x",
                                        "required": true
                                    },
                                    "y": {
                                        "type": "number",
                                        "id": "http://jsonschema.net/volume/position/y",
                                        "required": true
                                    }
                                }
                            }
                        }
                    }
                }
            }
          
+ Response 201 (application/json)
